spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connectwave
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
    hibernate:
      ddl-auto: update
  jpa-show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG